# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT09 < Formula
  desc "Configuration management for Robotics"
  homepage "https://docs.mirurobotics.com"
  version "0.9.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.9.1/cli_Darwin_x86_64.tar.gz"
      sha256 "5b6badae8d69bcf5ba7c458582908dfd7fb0f1fb90ef284b51fdf99c89d1a228"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.9.1/cli_Darwin_arm64.tar.gz"
      sha256 "3805c7ab4c58c4af5d0174d65c29696598d367d1ee23a3269bde97c866732994"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.9.1/cli_Linux_x86_64.tar.gz"
      sha256 "9aba636752a40ff70198eabb8f79217096d449af6a4db82040cfcf1864e7a57e"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.9.1/cli_Linux_arm64.tar.gz"
      sha256 "991d33d5e8eb58f05623e1f36d0da034ae41c3b87e63fcd355373bb13342b47c"
      def install
        bin.install "miru"
      end
    end
  end
end
