# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0121Beta4 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.12.1-beta.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.1-beta.4/cli_Darwin_x86_64.tar.gz"
      sha256 "6fc675a004cf905cc6a7adf2b6d4a4cfe8cec6149008961bc35e8f407adde10c"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.1-beta.4/cli_Darwin_arm64.tar.gz"
      sha256 "6a572de818d988522fd855bb3d35f1091a71f93e15da33d2976bcc12e51f63f2"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.1-beta.4/cli_Linux_x86_64.tar.gz"
      sha256 "302d126bb7cfa3768d9ccf2f271ec61cddb5a68fb626a8f4ae71fd596d25d6ae"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.1-beta.4/cli_Linux_arm64.tar.gz"
      sha256 "5ff079f04873faf783d472a4dd50619d6fadd1298a461e87066bd1aa313684e9"
      def install
        bin.install "miru"
      end
    end
  end
end
