# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0100Beta1 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.0-beta.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.0-beta.1/cli_Darwin_x86_64.tar.gz"
      sha256 "49aef966318b361a813a2be7b544dadf1d296473db1dea9b01c795c9df92d5e9"

      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.0-beta.1/cli_Darwin_arm64.tar.gz"
      sha256 "4436ac5498fd887a3eed07bb99231ef85e091dc518b619e4aea057f8896af745"

      define_method(:install) do
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.0-beta.1/cli_Linux_x86_64.tar.gz"
      sha256 "36e3a6dba56dac73ded3e8d4ab447bc35afa4a46f6cbb8d29f8dea986e2427e3"
      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.0-beta.1/cli_Linux_arm64.tar.gz"
      sha256 "f0dd1ad5f6b79a81ce4fddeff629aab4234d91a25942edab3bf4d199f2869ba9"
      define_method(:install) do
        bin.install "miru"
      end
    end
  end
end
