# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0111Beta4 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.11.1-beta.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.4/cli_Darwin_x86_64.tar.gz"
      sha256 "e43645f4ee08320433970f7c79be162928419facb9e06fee1fc0507a01d0b3ba"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.4/cli_Darwin_arm64.tar.gz"
      sha256 "60c9cdc2863ee2f83a4c306638ee1c227d2b3cf9b7e075be74b5a01f727ceca7"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.4/cli_Linux_x86_64.tar.gz"
      sha256 "9cbd100236faa01edbcf3e58a940956f69482c3c1e2de3be3740def3d74f5988"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.4/cli_Linux_arm64.tar.gz"
      sha256 "c41163f0341054444d33fe19ba3e9ba49f743a9187841ac255ca221b31eefe5d"
      def install
        bin.install "miru"
      end
    end
  end
end
