# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0101Alpha1 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.1-alpha.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.1/cli_Darwin_x86_64.tar.gz"
      sha256 "043d1c07298017aea118a0cbc5094b82286d4032f5ffe5396fa4894e707cf1f2"

      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.1/cli_Darwin_arm64.tar.gz"
      sha256 "f15cabba33697ef90b9da65646cc46a266765ac6901ec081a510c7ce928c3a46"

      define_method(:install) do
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.1/cli_Linux_x86_64.tar.gz"
      sha256 "56ed5ed590cdc56c9e6340f82f8790755ef64b864cfbad850c2bb71ea2ce43dd"
      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.1/cli_Linux_arm64.tar.gz"
      sha256 "37dabe1788a5b5aef07fe2975691d0fa0a20694393a903c95ba508ae51cc9f98"
      define_method(:install) do
        bin.install "miru"
      end
    end
  end
end
