# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0121Beta1 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.12.1-beta.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.1-beta.1/cli_Darwin_x86_64.tar.gz"
      sha256 "880aef4f8024f45b5afdfc19871c21a8537f2e96e32d91bc898423667e2d1ada"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.1-beta.1/cli_Darwin_arm64.tar.gz"
      sha256 "ca4097d4ddc8d143afb024cd284e4cf11973aa251ca8283e28b98f7b16e61295"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.1-beta.1/cli_Linux_x86_64.tar.gz"
      sha256 "11eb63faa1f9c95aca11669342282f7e5cb7005ca488cfebf5986a5ec2bdd769"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.1-beta.1/cli_Linux_arm64.tar.gz"
      sha256 "aa20ddbf3f7d8147e906e6ff3ba32de34972a32854ca983fc7d9568d4b922edc"
      def install
        bin.install "miru"
      end
    end
  end
end
