# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0101Alpha5 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.1-alpha.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.5/cli_Darwin_x86_64.tar.gz"
      sha256 "b5ef7a89d6e5281c228dd814dfe07b539a1aa2347fe88dcc983f55948ace01d3"

      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.5/cli_Darwin_arm64.tar.gz"
      sha256 "3e1b306aaab58b52e88e8720dcfc4f2afa7a393fc93fc3ec52a358063b588cb2"

      define_method(:install) do
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.5/cli_Linux_x86_64.tar.gz"
      sha256 "fdfad70fd62e3c9580ef93443ca7b2978d812de7d9dc0ac88c0ab1f29d18535f"
      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.5/cli_Linux_arm64.tar.gz"
      sha256 "902fdd401e2bf1583ba4de67c3a9b1bc58fb8172a283aff7a111122c629b3460"
      define_method(:install) do
        bin.install "miru"
      end
    end
  end
end
