# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miru < Formula
  desc "Configuration management for Robotics"
  homepage "https://docs.mirurobotics.com"
  version "0.9.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.9.2/cli_Darwin_x86_64.tar.gz"
      sha256 "0201b98a2c22d28005efdcde02aa07d62f544208bdebfe0bd5cdddccf9994054"

      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.9.2/cli_Darwin_arm64.tar.gz"
      sha256 "21b7d5a564398c873f16cb4082390eebd89b987eb3a839683c2bf64af1183e90"

      define_method(:install) do
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.9.2/cli_Linux_x86_64.tar.gz"
      sha256 "8a20147031a395e1410296fef440558250ccb0f2775c4aba894b0971e5407f81"
      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.9.2/cli_Linux_arm64.tar.gz"
      sha256 "d614ff87d8d679a0982ccd3e140a876dfbdf9c1290dc4c1f2b4b584159832dc0"
      define_method(:install) do
        bin.install "miru"
      end
    end
  end
end
