# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0111Beta3 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.11.1-beta.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.3/cli_Darwin_x86_64.tar.gz"
      sha256 "1be5ff3206b191533e3c72537ccf137d3b632d8d1dc8613559b4d84b31efec29"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.3/cli_Darwin_arm64.tar.gz"
      sha256 "555869bac1c627d5b0af42aba564e7dae55d2f6d302626d18a3a166177c054cc"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.3/cli_Linux_x86_64.tar.gz"
      sha256 "8acb4a973f71c23c384a6c3a9bbe5fa9f1b94c6a6b8a6f46c77a1798ea72e858"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.3/cli_Linux_arm64.tar.gz"
      sha256 "4d9805907cc3633ba44b8acc2cf6973daa55cf998103bcf14a47188676496c3d"
      def install
        bin.install "miru"
      end
    end
  end
end
