# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miru < Formula
  desc "Configuration management for Robotics"
  homepage "https://docs.mirurobotics.com"
  version "0.10.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1/cli_Darwin_x86_64.tar.gz"
      sha256 "00a98b4ea14fc13a59fb6173f95b24c3e8bce4a1ee6ee1fd75da65460870e9c2"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1/cli_Darwin_arm64.tar.gz"
      sha256 "830b9f79764946f58fb7a2e4a75f180f53944fe7ad33c1fa2fdb0e7e3bf0e16d"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1/cli_Linux_x86_64.tar.gz"
      sha256 "8f077ba0d38ebc611f2379f2e1decb28bdb02ab5614fb9132bb0a4a9a96b7aa7"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1/cli_Linux_arm64.tar.gz"
      sha256 "5506a68a91e18c10ccb92852a488a494fcc891b646957ee6dd438003eb5ed615"
      def install
        bin.install "miru"
      end
    end
  end
end
