# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0 < Formula
  desc "Configuration management for Robotics"
  homepage "https://docs.mirurobotics.com"
  version "0.11.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1/cli_Darwin_x86_64.tar.gz"
      sha256 "5ce53792e66f55a6bbdba37acf8961b9d5e6e78122d53e3a0500ba789e06fbc9"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1/cli_Darwin_arm64.tar.gz"
      sha256 "c0871529be4beee5a2fabb5ccd2e0a72887609d90f4b1bd82017ab8419d591ba"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1/cli_Linux_x86_64.tar.gz"
      sha256 "d0cd017f7f5b63950f0d68f5ca4ce30a822cc2cc2ea3e1feb97fe8b4e6138f67"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1/cli_Linux_arm64.tar.gz"
      sha256 "c7b5cf2ecf7fd808b133562bac38e29ceac7f7dbea4c7ac148b78e431dbc9c51"
      def install
        bin.install "miru"
      end
    end
  end
end
