# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0111Beta7 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.11.1-beta.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.7/cli_Darwin_x86_64.tar.gz"
      sha256 "f152211eb2c6c1c29c464509bde7141a7f2cc38d8b066890785e89a9a87bb471"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.7/cli_Darwin_arm64.tar.gz"
      sha256 "316d4eff37684845ef61e5b6a27752d3766545683574ac2a51c45f9217d323d5"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.7/cli_Linux_x86_64.tar.gz"
      sha256 "5b5da8761e9f9be9b86377fa75e2f718a1be5bf0fecf83a5e7ae480f66a10301"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.7/cli_Linux_arm64.tar.gz"
      sha256 "5e5202b46299e0f131a2f7fd010396c11490fa46b0113ef5b1a90c883c0691c0"
      def install
        bin.install "miru"
      end
    end
  end
end
