# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0102Beta4 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.2-beta.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-beta.4/cli_Darwin_x86_64.tar.gz"
      sha256 "a0781bd6224d3b2bd530cb7cbcdf7c5bb65aa329de91944c156c0643596021d7"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-beta.4/cli_Darwin_arm64.tar.gz"
      sha256 "75b08413fe499d668e63658a8a4f1de14566c2a4c9ebe13f005aa4665ac72755"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-beta.4/cli_Linux_x86_64.tar.gz"
      sha256 "cef58038d54d183d5bd72e704e4f0e06b3cba24a13fbfd4efd046d4f863c1ce1"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-beta.4/cli_Linux_arm64.tar.gz"
      sha256 "6cfc19121e25a5d8e0f5a396bba56471c7cca36865c01e61acd5e114d4533351"
      def install
        bin.install "miru"
      end
    end
  end
end
