# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0101Alpha7 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.1-alpha.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.7/cli_Darwin_x86_64.tar.gz"
      sha256 "093782dd74c2095ccbb6cade5ca2a1a13c40f2afb172f344e89c2083f44ab6d7"

      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.7/cli_Darwin_arm64.tar.gz"
      sha256 "c7d54f862fe7642e9e515338a365aa8eaa6472451232f26d8487a79112fd8d23"

      define_method(:install) do
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.7/cli_Linux_x86_64.tar.gz"
      sha256 "ad917a0f2e043d1a71734a8d05fa858676deb3841f2debb04b8702d170d9ef69"
      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.7/cli_Linux_arm64.tar.gz"
      sha256 "fdf863a2b9007847fb7fcaca9a6afc093f5b47e6daa9dbcc6467e88478647251"
      define_method(:install) do
        bin.install "miru"
      end
    end
  end
end
