# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0101Alpha4 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.1-alpha.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.4/cli_Darwin_x86_64.tar.gz"
      sha256 "84f60c35e2d1811a67fa794bcfd421fe924a6df1c4bc75e26910573d8421807e"

      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.4/cli_Darwin_arm64.tar.gz"
      sha256 "12ee276f5c3b9b2cd016f2ec8925495a01ae880429b9929fa7b6aafc6e0cf398"

      define_method(:install) do
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.4/cli_Linux_x86_64.tar.gz"
      sha256 "d32e4c21a9be4ef8c475ed70a2bc1507a04efc9b04dabb0fd00d1ead8b15f30c"
      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.4/cli_Linux_arm64.tar.gz"
      sha256 "846727deb88239b6c3d40abc3743ca18b7f16e64ef886fcb978ba0d1796afd4c"
      define_method(:install) do
        bin.install "miru"
      end
    end
  end
end
