# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0100Beta2 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.0-beta.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.0-beta.2/cli_Darwin_x86_64.tar.gz"
      sha256 "3db85c11e7cbabcbd848834ed547196d099c99398d1dc3d5704c99c7ac8e68a2"

      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.0-beta.2/cli_Darwin_arm64.tar.gz"
      sha256 "9fac17cc16415d3f5556236898cd98dabda21d4b6a9da53c348fc56f98c8f427"

      define_method(:install) do
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.0-beta.2/cli_Linux_x86_64.tar.gz"
      sha256 "1173b49a0e72f107923ea00cb4348285dc5493781607e59591c8578ed9ff6c4f"
      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.0-beta.2/cli_Linux_arm64.tar.gz"
      sha256 "6d5354434f699953472cee86726f98ba3d5efabe8e7ec4e3bc093b521a474d3f"
      define_method(:install) do
        bin.install "miru"
      end
    end
  end
end
