# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0111Beta5 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.11.1-beta.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.5/cli_Darwin_x86_64.tar.gz"
      sha256 "0b6d9f66c01560bd7ec7f76d587d3933d06832f4babd29929cf6f8e42c09c99b"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.5/cli_Darwin_arm64.tar.gz"
      sha256 "a14117d3d8606294e5c14c47a5f79adeb8f3e0d29edc1eff19dd170b5b3768ca"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.5/cli_Linux_x86_64.tar.gz"
      sha256 "de7e63283f4d6f99884af675079d04fd258ce75db43d2208aa0827fca5f0e904"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.5/cli_Linux_arm64.tar.gz"
      sha256 "fdf56b9e6321a6d56807fede8ccca640f83e9901decbec1c67fb0ac09c598af0"
      def install
        bin.install "miru"
      end
    end
  end
end
