# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT012 < Formula
  desc "Configuration management for Robotics"
  homepage "https://docs.mirurobotics.com"
  version "0.12.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.0/cli_Darwin_x86_64.tar.gz"
      sha256 "2d2e80df5b2614c6f39e4af46f275f712bc4a34c74262885ee626bdc07d21845"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.0/cli_Darwin_arm64.tar.gz"
      sha256 "a7d22698a734b918e65270372c0ea3d863d53fdaa757acc7c3c77573f10e763e"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.0/cli_Linux_x86_64.tar.gz"
      sha256 "d93e40e3113a2e4cb8b723e72e145a5708f58922860d1150ec4c571b2c161e6d"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.0/cli_Linux_arm64.tar.gz"
      sha256 "6b04b46bff77fa5edaf058d83cd91061bfb9fed94ed4f89e892f661b0ce070b6"
      def install
        bin.install "miru"
      end
    end
  end
end
