# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT091Beta1 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.9.1-beta.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.9.1-beta.1/cli_Darwin_x86_64.tar.gz"
      sha256 "026e59c9701512ba6e6b8611dee101907280188b10e576b1da20b24df3138705"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.9.1-beta.1/cli_Darwin_arm64.tar.gz"
      sha256 "050befb1b9c56de580b643fd05b8f80c4a7157f55773024902e2d22c58c6e59b"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.9.1-beta.1/cli_Linux_x86_64.tar.gz"
      sha256 "d70df6943520073bf7ec5aa56042774aa30cd8d2262505246e51509c22a2aa20"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.9.1-beta.1/cli_Linux_arm64.tar.gz"
      sha256 "4e10f9a1919cd0d152dc4a333add11138a8ab1db5b8783b0557646d7afb24d5b"
      def install
        bin.install "miru"
      end
    end
  end
end
