# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0102Beta1 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.2-beta.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-beta.1/cli_Darwin_x86_64.tar.gz"
      sha256 "79855695371b90f79f54afa954ffac16d2f54ee487459cce85b94111888769b7"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-beta.1/cli_Darwin_arm64.tar.gz"
      sha256 "e0c573848dfc0d505ab4a6271812e4c23ff1077c5cc21488896fc5dad4367a12"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-beta.1/cli_Linux_x86_64.tar.gz"
      sha256 "4b904a84f5ca6985973ce4c995900b2c7811ded75c97e2650b8de8965e043843"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-beta.1/cli_Linux_arm64.tar.gz"
      sha256 "eb0611fca2d90ccc6d0f7ce7f3083b6f7f47296a08955a2156fb4ed37958cb58"
      def install
        bin.install "miru"
      end
    end
  end
end
