# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0121Beta3 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.12.1-beta.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.1-beta.3/cli_Darwin_x86_64.tar.gz"
      sha256 "632f041f506eb05b03a7b11fb6e64f26fb8aa8ca5b471bea5f138773621b5046"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.1-beta.3/cli_Darwin_arm64.tar.gz"
      sha256 "02993832bac70d599cc3d13e9b161d44cf411bfb096edf8e26d95b8654fd2d47"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.1-beta.3/cli_Linux_x86_64.tar.gz"
      sha256 "d447276dc09a7f7df8c3dca312e5eea340184cc22c40b00c252f551b4de425d9"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.1-beta.3/cli_Linux_arm64.tar.gz"
      sha256 "8a70bc3cb6f648992b53baf7edb678e41a5152070092b35d92277c848ef0ccf4"
      def install
        bin.install "miru"
      end
    end
  end
end
