# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0104Beta2 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.4-beta.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.4-beta.2/cli_Darwin_x86_64.tar.gz"
      sha256 "4a415a6d825714b48934f77266b468b91f9f29d830e2047bb01e313c24f2e3d8"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.4-beta.2/cli_Darwin_arm64.tar.gz"
      sha256 "ebc39676418e017bfadf25fe0f2f778a30610549f3baddef455c4da3403a79da"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.4-beta.2/cli_Linux_x86_64.tar.gz"
      sha256 "4868e390270e55f57bfe2433ea58f6dc41a62ae0d0aa3dad5f5527c7147988a6"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.4-beta.2/cli_Linux_arm64.tar.gz"
      sha256 "1eb9a5bfd3e5efa119c736758611f8fa992b9cd2ca97267524c59b1909cbe8b3"
      def install
        bin.install "miru"
      end
    end
  end
end
