# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0101Alpha6 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.1-alpha.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.6/cli_Darwin_x86_64.tar.gz"
      sha256 "a7d6dcc9faac0904d3f668e7553fb1384f3346ce6b0f14b9e7f95a40041298f0"

      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.6/cli_Darwin_arm64.tar.gz"
      sha256 "9123bbf505294c5ff1377518f7842c615337e8ffbfc98217c9ce7ad180a92a56"

      define_method(:install) do
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.6/cli_Linux_x86_64.tar.gz"
      sha256 "effcbfa1c78f321ca0a478f837c1330cf7b78bc7c2dfe33d805be4742f15767e"
      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.6/cli_Linux_arm64.tar.gz"
      sha256 "5886acf8fb55816274c1123b703b3a31ee83239998ae86e02ca236ec86113b23"
      define_method(:install) do
        bin.install "miru"
      end
    end
  end
end
