# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT091Beta2 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.9.1-beta.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.9.1-beta.2/cli_Darwin_x86_64.tar.gz"
      sha256 "3b2d72fc44355f5b58861ab7212aab4111833db92d62e1b67e5ceb2039e2b0a9"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.9.1-beta.2/cli_Darwin_arm64.tar.gz"
      sha256 "d03392f31acf1680cdd589b92d565ffa3bed570ffea32dea78596724610a8ab6"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.9.1-beta.2/cli_Linux_x86_64.tar.gz"
      sha256 "462c9805e0d035c07cecdea2945f1947ce279fa3e8cbf6fbaf9b560ca8467ab1"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.9.1-beta.2/cli_Linux_arm64.tar.gz"
      sha256 "1314eacebef59fbfcf9004bd9a8c1be28c0163d5a04fddb1237daa7c90fa3d6b"
      def install
        bin.install "miru"
      end
    end
  end
end
