# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0111Beta10 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.11.1-beta.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.10/cli_Darwin_x86_64.tar.gz"
      sha256 "a0384564f61d3c5bc0ea3fb0494ec281960b466646c328e603fccc82499b98b5"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.10/cli_Darwin_arm64.tar.gz"
      sha256 "f504c9abdfbed505f56aaf80f6e58f7af465806ae14d9528f6cdbb10bdb2d077"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.10/cli_Linux_x86_64.tar.gz"
      sha256 "ef729c44750ef5451fbd4c0f9fe7e737073c9d5fd743009d727d40d3d9b55588"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.10/cli_Linux_arm64.tar.gz"
      sha256 "29eb13b7bdfb458395816096628060ef82fb01ea1e7d4b600273c9986a968e00"
      def install
        bin.install "miru"
      end
    end
  end
end
