# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0100 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.0/cli_Darwin_x86_64.tar.gz"
      sha256 "47cde3c79129a173fcf711e9f3a3f2fb81e4a90d91a58035ae31dccb2721070e"

      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.0/cli_Darwin_arm64.tar.gz"
      sha256 "d1c3f69d1080610fb03d50915c39e9d686a24cd7307f5c82c6ddf6e4851e1793"

      define_method(:install) do
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.0/cli_Linux_x86_64.tar.gz"
      sha256 "1e1a7e39f8e2fdb6d06bdfec1f180ecca08bb4f4eb97baf4cbfefc79783c3d7a"
      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.0/cli_Linux_arm64.tar.gz"
      sha256 "7c7f4e07f791cbb83b1c7e4bec3a4dae24d40ac160962f0fd7ce725270f3b2e5"
      define_method(:install) do
        bin.install "miru"
      end
    end
  end
end
