# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0104Beta1 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.4-beta.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.4-beta.1/cli_Darwin_x86_64.tar.gz"
      sha256 "6d9b08ee2a7eb38ee9ec40c4f50f8f81251aa066a91b785ed82a8c2c2686e029"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.4-beta.1/cli_Darwin_arm64.tar.gz"
      sha256 "b5a4aee8e7671fad45a0a8e415fe547221cf8362be6f329430397f8687b3b256"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.4-beta.1/cli_Linux_x86_64.tar.gz"
      sha256 "7a848b737ba56f2885e7a72d823612fe2173c9e41c2ae6fa486c9d9d87e2ce18"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.4-beta.1/cli_Linux_arm64.tar.gz"
      sha256 "d635d81f73b96bc601c8a7c4f54c1c565ea36c7b1acdad2690fff513aeb2dbf2"
      def install
        bin.install "miru"
      end
    end
  end
end
