# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0101Beta1 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.1-beta.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-beta.1/cli_Darwin_x86_64.tar.gz"
      sha256 "57d80b784d45a43f7a8788b67934af8990fc1f609bfd8d2037dcddbb3be7e4bd"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-beta.1/cli_Darwin_arm64.tar.gz"
      sha256 "69b9983c8236b82aa822388f6f4fe8aa33e39a830366489458d56fc5ac7fd158"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-beta.1/cli_Linux_x86_64.tar.gz"
      sha256 "7845b9aecefd5ef79275ffbc2447bf8a4c1928c1cca1745922ad275823752fcb"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-beta.1/cli_Linux_arm64.tar.gz"
      sha256 "435c38e7b44c9a936a1244d4ea6ff980d155008065b935798ea145a7b229f412"
      def install
        bin.install "miru"
      end
    end
  end
end
