# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0111Beta9 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.11.1-beta.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.9/cli_Darwin_x86_64.tar.gz"
      sha256 "2af027648e6f9d0f0a310ab54341e614db0a5c367b3e8b819ef18d3dcec57f68"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.9/cli_Darwin_arm64.tar.gz"
      sha256 "215c7a612389fed44b52e104f1f54c6009bea59458a98c344567dba93fdb4544"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.9/cli_Linux_x86_64.tar.gz"
      sha256 "7b4247ae216bda3a8c1a3c186dca968a13add7095b497816c5ff41118bcdb4b7"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.9/cli_Linux_arm64.tar.gz"
      sha256 "c5c21986e487d20376752130745a2c83b5e301838518051a319b0da0e97f7cd6"
      def install
        bin.install "miru"
      end
    end
  end
end
