# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0101Alpha2 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.1-alpha.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.2/cli_Darwin_x86_64.tar.gz"
      sha256 "24694044ddfd0034ba9d2e4080891924ec0cd80a8429ebc12c42d454dd4879ea"

      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.2/cli_Darwin_arm64.tar.gz"
      sha256 "59c42ec725dafffe6181a59a9f9d68cf6d6038daeb309b2558ff680bc9507744"

      define_method(:install) do
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.2/cli_Linux_x86_64.tar.gz"
      sha256 "49919b3352e7384139955f55be0c1d12690885693504074e12572ec4f3839b95"
      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.2/cli_Linux_arm64.tar.gz"
      sha256 "7a004bccfc182ddefcf41dcb1c73087d6d00d2a79869fb5cbc3b102966a798e0"
      define_method(:install) do
        bin.install "miru"
      end
    end
  end
end
