# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0102Beta3 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.2-beta.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-beta.3/cli_Darwin_x86_64.tar.gz"
      sha256 "3aa77eb51b36c84dfd26477d9e60f0c10660340fb337b3c157b81ba054b11c28"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-beta.3/cli_Darwin_arm64.tar.gz"
      sha256 "7beaf8674069140e5a017bc536cb981e4fdda768acb8c177cb408a55a8f215d2"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-beta.3/cli_Linux_x86_64.tar.gz"
      sha256 "0075c528ce132b108dd62c0dcf7c125d62e692e38309002694b838409f0949e0"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-beta.3/cli_Linux_arm64.tar.gz"
      sha256 "cb2cd8094d7fa5120f99f62be9111e168225fefc1bff533ceccf7cf7d72ec45f"
      def install
        bin.install "miru"
      end
    end
  end
end
