# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0111Beta2 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.11.1-beta.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.2/cli_Darwin_x86_64.tar.gz"
      sha256 "6da9ca7321bd18f468ec2ddaea39e1a4c1c3c0cc799f1ac2163d3325074b2b6d"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.2/cli_Darwin_arm64.tar.gz"
      sha256 "9184053a2ad1b8ca92a1ba624b6c94abb28d818509a54e6093dcf68941da5102"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.2/cli_Linux_x86_64.tar.gz"
      sha256 "bd8417c66af7a2acf318907a12843ef03779a1cd5b2ab71436b282109344939f"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.2/cli_Linux_arm64.tar.gz"
      sha256 "7aeb55c3ecf197b8d1f54129612d3e89858d122f95f63e5c40ceef9fe2ee3f65"
      def install
        bin.install "miru"
      end
    end
  end
end
