# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0101Alpha9 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.1-alpha.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.9/cli_Darwin_x86_64.tar.gz"
      sha256 "674a17e87ab867db50e4461e440e48ec93f32435261a1b4a911c7ca3176985fb"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.9/cli_Darwin_arm64.tar.gz"
      sha256 "e2f7643ba02e132948f42d1cc268351195b3f860ea04a4bc4a65c08d4e0dd4f0"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.9/cli_Linux_x86_64.tar.gz"
      sha256 "6cd2d15b7e8d99fd28bc81c5d9127fdfb3b747bb694dd19dff0fa9943bb72d44"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.9/cli_Linux_arm64.tar.gz"
      sha256 "a857ec8f1df05e52039cdd0533fc00d9280cfcdf38b67ed1a37ef56b2e8c66c3"
      def install
        bin.install "miru"
      end
    end
  end
end
