# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0111Beta1 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.11.1-beta.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.1/cli_Darwin_x86_64.tar.gz"
      sha256 "333b4231c2fef5cbdee7fc5bf2606d812a31c03f79f518658d4342f98e2bc4f0"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.1/cli_Darwin_arm64.tar.gz"
      sha256 "8045f6a2af040d970fafbb4b6601f94ba5a89acbcd828d903ac9bfd32ef6a9a5"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.1/cli_Linux_x86_64.tar.gz"
      sha256 "4e9a5767280880306f95eb56c1f1d2fff71429c089d085302324fbcafd4570d6"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.1/cli_Linux_arm64.tar.gz"
      sha256 "cb02bb4fdee265c28f68b09c4ef2ce2babf40cb2a71985c73e4d64f04998a48a"
      def install
        bin.install "miru"
      end
    end
  end
end
