# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0110Beta1 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.11.0-beta.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.0-beta.1/cli_Darwin_x86_64.tar.gz"
      sha256 "4132b524fe2ff02ead943e7895623dca0a3b48c3b6882204f962932e7e095b0b"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.0-beta.1/cli_Darwin_arm64.tar.gz"
      sha256 "780513cfdfb6cc4bcf664eb2254fa8ae6a9330dbb67bed2bf5734b5123ad4eba"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.0-beta.1/cli_Linux_x86_64.tar.gz"
      sha256 "e8af90f7ea248bd4a84881541597c34a450533142840bc7136567cda8553c08a"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.0-beta.1/cli_Linux_arm64.tar.gz"
      sha256 "2cf6428253c33efabc7b686d03ed5c988894fe2f7a1669d1e78409115c27c8c6"
      def install
        bin.install "miru"
      end
    end
  end
end
