# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0121Beta2 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.12.1-beta.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.1-beta.2/cli_Darwin_x86_64.tar.gz"
      sha256 "4e484f0c7a61e409e21e19ffa27e8eefab4ba2d549df64c9b682e275b1ee1a1a"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.1-beta.2/cli_Darwin_arm64.tar.gz"
      sha256 "06cd3e37005b3714aad838a06057c15a99cb7741aedafbd38be35c49afcb59d8"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.1-beta.2/cli_Linux_x86_64.tar.gz"
      sha256 "a2d11b1cc73d67cd2297fa28047e4702a8d8722aa480ac8895c01afa634f01ba"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.12.1-beta.2/cli_Linux_arm64.tar.gz"
      sha256 "4411d0bfe0d082d2fd3519c32a1fc096f0a57061b6f05c79cc34ce83985bf657"
      def install
        bin.install "miru"
      end
    end
  end
end
