# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0101Alpha3 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.1-alpha.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.3/cli_Darwin_x86_64.tar.gz"
      sha256 "0aa9fa45e1a094b9c89b8d2ff041a4e086a3fbfc74b46fcfcd6a731d3d79bc1e"

      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.3/cli_Darwin_arm64.tar.gz"
      sha256 "e6ee1e60ff9cf7c0d5e6693c670f374c5c4ca3ead41b944b4da3d3aed307b9fd"

      define_method(:install) do
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.3/cli_Linux_x86_64.tar.gz"
      sha256 "34708d6ca85cd7960504c198aba4e018791eb59b7b3c4764759c82535b39e186"
      define_method(:install) do
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.1-alpha.3/cli_Linux_arm64.tar.gz"
      sha256 "e0475a431ebaf2fa796907a38c4f6083d9ccaf9e41db00f8ab289920f2e6b55f"
      define_method(:install) do
        bin.install "miru"
      end
    end
  end
end
