# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0102Alpha1 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.2-alpha.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-alpha.1/cli_Darwin_x86_64.tar.gz"
      sha256 "73868bcc39f1fb392786b17c842127ffa7b8755878b32f79b0d9b770a1bfdab9"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-alpha.1/cli_Darwin_arm64.tar.gz"
      sha256 "5895aff2ee64941873a15a178a404a181427a363b4c7e0787e419a77eb7f8f20"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-alpha.1/cli_Linux_x86_64.tar.gz"
      sha256 "c5cd74e102a49fe6a60cddaf0acee8612a640cae6ad1745081a73f3979d02dc0"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-alpha.1/cli_Linux_arm64.tar.gz"
      sha256 "f3fd813c83b2a59f9f95a16595d42f68bb280170b1547531f9ca22bf5d129b77"
      def install
        bin.install "miru"
      end
    end
  end
end
