# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0102Beta2 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.2-beta.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-beta.2/cli_Darwin_x86_64.tar.gz"
      sha256 "01ac80b882ac730142bacb7ce9531fc991775bc2dd3ed8f61947bae145a79909"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-beta.2/cli_Darwin_arm64.tar.gz"
      sha256 "40e3d67ae3bae5ca5d5b3e98864707d45a20e4fa7d3d13318df1577740052304"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-beta.2/cli_Linux_x86_64.tar.gz"
      sha256 "c2be5d3e4b937e5be5a58fa8719ebb21687b4f60cafead6345ebb60f0bdd14fa"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2-beta.2/cli_Linux_arm64.tar.gz"
      sha256 "d9e35c1e2789830e01559ad4f173662ed3760b7e2636932fff24206b536c9cda"
      def install
        bin.install "miru"
      end
    end
  end
end
