# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miru < Formula
  desc "Configuration management for Robotics"
  homepage "https://docs.mirurobotics.com"
  version "0.11.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.0/cli_Darwin_x86_64.tar.gz"
      sha256 "96d737ff4d727fefaea32572adaef8b395cf413a46a68a48aff84fbd82374e2a"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.0/cli_Darwin_arm64.tar.gz"
      sha256 "d4589f4ebca95e8efe59bc2ce07b55d1e447d130b31ad1510d37640b214ee833"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.0/cli_Linux_x86_64.tar.gz"
      sha256 "a54447e3d5dbe4b9babcc175fec1e319cbb6c16e6b7fe7a3c0e07c9604655d25"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.0/cli_Linux_arm64.tar.gz"
      sha256 "781f0805fcf33df2ff9a484fa6b1921ffeb5b57308d9812cc05ab7c551b8b11c"
      def install
        bin.install "miru"
      end
    end
  end
end
