# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0111Beta8 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.11.1-beta.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.8/cli_Darwin_x86_64.tar.gz"
      sha256 "fb30df5578aa0a7c8caa53cb69e48747492093daf2a6977d8850840f2e87f632"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.8/cli_Darwin_arm64.tar.gz"
      sha256 "28ed31448b0147175907cf026945282ee47d85500710c889e466e4af2c2ddf67"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.8/cli_Linux_x86_64.tar.gz"
      sha256 "74ed63f31ef8585b3c2ae7b4c4b7dca5860acdf6291c4892cc6cb8120c000cd8"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.8/cli_Linux_arm64.tar.gz"
      sha256 "f755112aab39be6465fa6a9f3906a103bb8cea37ea56f0121b55955d43a25f89"
      def install
        bin.install "miru"
      end
    end
  end
end
