# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0103Beta1 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.3-beta.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.3-beta.1/cli_Darwin_x86_64.tar.gz"
      sha256 "f55dbc518b44bcf4dc811d988dadd36df1dbab5ac12853f053587df9c1120117"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.3-beta.1/cli_Darwin_arm64.tar.gz"
      sha256 "f5dfd7a450c1efccd5f3703fe623a67edbe6fbe7dadc8962a14a58e8f6754626"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.3-beta.1/cli_Linux_x86_64.tar.gz"
      sha256 "e0c3ed5aa54e565a6e72bff8a31c65c339b7e76f864fc3aa4bb3ddd5cdbcdcdd"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.3-beta.1/cli_Linux_arm64.tar.gz"
      sha256 "16cd69db42b51077954581d5efc5191d21cd69a1c4729b2294c3986a51634c88"
      def install
        bin.install "miru"
      end
    end
  end
end
