# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0102 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.10.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2/cli_Darwin_x86_64.tar.gz"
      sha256 "3c51340c1de1170dcdff598bbd5e615cacf7eb267971f79ec149d14bc72a8563"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2/cli_Darwin_arm64.tar.gz"
      sha256 "05785dd04bdfd3d88052de33f9ad37a486a10acef663fae691744cc1385ffc6a"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2/cli_Linux_x86_64.tar.gz"
      sha256 "c87b54a36eca63b956c6ed648026e36027061052967aa26dd7744badf9aa32a1"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.10.2/cli_Linux_arm64.tar.gz"
      sha256 "76b726dc29716ecf0385a0b782582a12cd0210ad4469530010f262903777492b"
      def install
        bin.install "miru"
      end
    end
  end
end
