# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0111Beta6 < Formula
  desc "Configuration management for Robotics (prerelease)"
  homepage "https://docs.mirurobotics.com"
  version "0.11.1-beta.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.6/cli_Darwin_x86_64.tar.gz"
      sha256 "2549b8b4fd569106465d5b4420401a213393ecc7ab7971f53a56065d57d352e2"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.6/cli_Darwin_arm64.tar.gz"
      sha256 "249aec4eebd2d671575e82ada80291e2799de08996f4be7a330695a33d7dfb77"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.6/cli_Linux_x86_64.tar.gz"
      sha256 "9d19a85374fb164e0a1976e5c693bbe2b11e48aca813b31c3ca867310808d2a0"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirurobotics/cli/releases/download/v0.11.1-beta.6/cli_Linux_arm64.tar.gz"
      sha256 "7f15a33c72b11b69ddfca6cc6018cff826fd9ce1f5b1f506e07eff0d9f1eed89"
      def install
        bin.install "miru"
      end
    end
  end
end
